language: python
# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required

before_install:
  - pip install restructuredtext_lint
  - pip install flake8 pycodestyle pep8-naming
  - flake8 .
  - rst-lint README.rst
  - export PATH=/usr/bin/:$PATH
  - pip install omego
  - (cd /tmp ; omego download python --release 5.4.0-m3 --sym=auto)
  - git clone --depth 1 -b web_diagnostics https://github.com/joshmoore/openmicroscopy /tmp/ome
  - pip install -r /tmp/ome/share/web/requirements-py27.txt

script:
    - sudo python setup.py sdist install --record files.txt
    - cat files.txt | xargs sudo rm -rf
    - sudo python setup.py bdist_egg
    - easy_install dist/*.egg
    - env PYTHONPATH=/tmp/ome/components/tools/OmeroPy/src/:/tmp/OMERO.py/lib/python /tmp/OMERO.py/bin/omero diagnostics
